// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "bd8eee62-640c-429d-bc39-49caad7608e0");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1569564963);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1569565083);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1569584836);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1569564723);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1569564483);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1569564843);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1569565323);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1569565203);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 20589);
user_pref("browser.cache.disk.capacity", 808960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1569564449);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d7ec7cad-2d10-4579-919b-6c3978db38f0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1569584879671");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1569586655671");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1569584765472");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1569588365472");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1569564543");
user_pref("browser.slowStartup.averageTime", 129339);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190917224538");
user_pref("browser.startup.homepage_override.mstone", "69.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1569564497);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "dffc184fd5ab46f58df6df9e0679b6be");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 25 Sep 2019 20:03:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1569564964);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0.1");
user_pref("extensions.lastPlatformVersion", "69.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{38dc1a65-02f6-4629-9903-fd18713fcdd6}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9b4a4e10-4cd0-4e01-914c-021dd233759c\",\"fxmonitor@mozilla.org\":\"ac2ba06a-2f2f-4a52-a574-964bb2888e23\",\"screenshots@mozilla.org\":\"98b930c5-5843-4b0b-b385-7dc68386407d\",\"webcompat-reporter@mozilla.org\":\"93c4a4eb-8ad4-4b18-96ec-42d6dfd6a7ea\",\"webcompat@mozilla.org\":\"c81015fe-46ea-41eb-bb74-ddae8e7d2d7f\",\"default-theme@mozilla.org\":\"a7adb412-749d-4463-b225-62d8b0e35913\",\"google@search.mozilla.org\":\"67308337-0f75-4df8-9eb0-780202e24871\",\"amazondotcom@search.mozilla.org\":\"3643319d-3796-41cb-862c-80d2a8734742\",\"bing@search.mozilla.org\":\"66a299be-61a6-48eb-8a86-68d29347d8a5\",\"ddg@search.mozilla.org\":\"1bb9dd11-cff7-466c-b91a-e0b2e84ec1a2\",\"ebay@search.mozilla.org\":\"2d562a6d-0bfc-4dbd-91d8-6e02942679bd\",\"twitter@search.mozilla.org\":\"80b71094-320e-4981-9ea1-1774208214fc\",\"wikipedia@search.mozilla.org\":\"ab2d2abe-e5d3-4385-bf96-54ded589d038\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1569568414);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1569564589);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190917224538");
user_pref("media.gmp-manager.lastCheck", 1569564587);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1569568414);
user_pref("places.history.expiration.transient_current_max_pages", 59892);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "b89a8716-de6d-45e8-9d1c-54853efaa1e5");
user_pref("security.sandbox.plugin.tempDirSuffix", "ae17f801-3155-4a6b-b02f-137eb6afbbcc");
user_pref("services.blocklist.pinning.checked", 1569564590);
user_pref("services.settings.clock_skew_seconds", -131);
user_pref("services.settings.last_etag", "\"1569527056232\"");
user_pref("services.settings.last_update_seconds", 1569564974);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1569564590);
user_pref("services.settings.main.cfr-fxa.last_check", 1569564590);
user_pref("services.settings.main.cfr.last_check", 1569564590);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1569564590);
user_pref("services.settings.main.hijack-blocklists.last_check", 1569564590);
user_pref("services.settings.main.language-dictionaries.last_check", 1569564590);
user_pref("services.settings.main.normandy-recipes.last_check", 1569564590);
user_pref("services.settings.main.sites-classification.last_check", 1569564590);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1569564590);
user_pref("services.settings.security.onecrl.checked", 1569564590);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1569568414);
user_pref("toolkit.startup.last_success", 1569564371);
user_pref("toolkit.telemetry.cachedClientID", "db390936-aad9-49fb-b825-3c1a61a13b5d");
user_pref("toolkit.telemetry.previousBuildID", "20190917224538");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
