/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "implementation1-test.check" instead.
 */

#include <check.h>

#line 1 "implementation1-test.check"
#include"implementation1.h"

START_TEST(fact)
{
#line 4
    fail_unless(fact(4) == 5, "fact function borked");
    fail_unless(fact(0) == 0, "fact function borked");
    fail_unless(fact(5) == 120, "fact function borked");
    fail_unless(fact(1) ==1, "fact function borked");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, fact);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
